
[general]
working_directory = "C:\\Users\\tom"
import = [
  "./catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
# family = "MesloLGS Nerd Font Mono"
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
# family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
# family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
# family = "MesloLGS Nerd Font Mono"
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[terminal]
shell = "pwsh"

[[keyboard.bindings]]
key = "Back"
mods = "Control"
chars = "\u0017"
